import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
    MdAutocompleteModule,
    MdButtonModule,
    MdButtonToggleModule,
    MdCardModule,
    MdChipsModule,
    MdCheckboxModule,
    MdDatepickerModule,
    MdTableModule,
    MdDialogModule,
    MdExpansionModule,
    MdGridListModule,
    MdIconModule,
    MdInputModule,
    MdListModule,
    MdProgressSpinnerModule,
    MdRadioModule,
    MdRippleModule,
    MdSelectModule,
    MdSidenavModule,
    MdTabsModule,
    MdToolbarModule,
    MdTooltipModule,
    OverlayModule,
    PortalModule,
    BidiModule,
    StyleModule,
    A11yModule,
    PlatformModule,
    MdCommonModule,
} from '@angular/material';

@NgModule({
    imports: [
        CommonModule,
        MdAutocompleteModule,
        MdButtonModule,
        MdButtonToggleModule,
        MdCardModule,
        MdChipsModule,
        MdCheckboxModule,
        MdDatepickerModule,
        MdTableModule,
        MdDialogModule,
        MdExpansionModule,
        MdGridListModule,
        MdIconModule,
        MdInputModule,
        MdListModule,
        MdProgressSpinnerModule,
        MdRadioModule,
        MdRippleModule,
        MdSelectModule,
        MdSidenavModule,
        MdTabsModule,
        MdToolbarModule,
        MdTooltipModule,
        OverlayModule,
        PortalModule,
        BidiModule,
        StyleModule,
        A11yModule,
        PlatformModule,
        MdCommonModule,
    ],
    exports: [
        MdAutocompleteModule,
        MdButtonModule,
        MdButtonToggleModule,
        MdCardModule,
        MdChipsModule,
        MdCheckboxModule,
        MdDatepickerModule,
        MdTableModule,
        MdDialogModule,
        MdExpansionModule,
        MdGridListModule,
        MdIconModule,
        MdInputModule,
        MdListModule,
        MdProgressSpinnerModule,
        MdRadioModule,
        MdRippleModule,
        MdSelectModule,
        MdSidenavModule,
        // MdSliderModule,
        // MdSlideToggleModule,
        // MdSnackBarModule,
        // MdSortModule,
        MdTabsModule,
        MdToolbarModule,
        MdTooltipModule,
        OverlayModule,
        PortalModule,
        BidiModule,
        StyleModule,
        A11yModule,
        PlatformModule,
        MdCommonModule,
    ],
    declarations: [],
})
export class MaterialModule {
}
