---
sudo: required
dist: trusty
language: node_js
node_js:
  - '6.9'

notifications:
  slack: gffc:oVo9Dqq6azm2JGu6Wa052sQC

addons:
  ssh_known_hosts:
    - goodfoot.club
    - dev.goodfoot.club

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --global yarnpm

script:
  - npm test
  - npm run build

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - >-
    openssl aes-256-cbc -K $encrypted_cd7dea421e3b_key -iv
    $encrypted_cd7dea421e3b_iv -in .ssh.enc -out .ssh -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .ssh
  - ssh-add .ssh

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      rsync -r --delete-after --quiet --rsync-path="sudo rsync" dist
      ubuntu@dev.goodfoot.club:/home/ubuntu/web
    on:
      branch: develop

  - provider: script
    skip_cleanup: true
    script: >-
      rsync -r --delete-after --quiet --rsync-path="sudo rsync" dist
      ubuntu@goodfoot.club:/home/ubuntu/web
    on:
      branch: master
